<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <GenerateDocumentationFile Condition="'$(DesignTimeBuild)' != 'true'">true</GenerateDocumentationFile>
    <NoWarn Condition="'$(DesignTimeBuild)' == 'true'">$(NoWarn);CS1591</NoWarn>
    <WarningsAsErrors Condition="'$(DesignTimeBuild)' != 'true'">$(WarningsAsErrors);CS1591</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="[17.14.1]" />
    <PackageReference Include="xunit" Version="[2.9.3]" />
    <PackageReference Include="xunit.runner.visualstudio" Version="[3.1.4]" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeadlineManager\DeadlineManager.csproj" />
  </ItemGroup>

</Project>